name: gel-paper-bench
channels:
  - bioconda
  - conda-forge
dependencies:
  - python>=3.11
  - pip
  - pip:
      - tsinfer==0.4.1
      - tsdate==0.2.3
      - tszip==0.2.5
      - tskit==0.6.4
      - stdpopsim==0.3.0
      - msprime==1.3.4
      - matplotlib>=3.10.0
      - numpy>=2.0.0
      - snakemake>=8.0.0
      - memray==1.19.1
      - pandas==2.3.3
      - seaborn==0.13.2
      - scipy==1.16.1
